INSERT INTO
  `permission`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by,
    is_hidden
  )
VALUES
  ( -- List
    'WebsiteApp',
    'Promo',
    'List',
    'Promo',
    'List',
    'GET',
    '/web/v1/promos',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Detail
    'WebsiteApp',
    'Promo',
    'View',
    'Promo',
    'View',
    'GET',
    '/web/v1/promos/:id',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Create
    'WebsiteApp',
    'Promo',
    'Create',
    'Promo',
    'Create',
    'POST',
    '/web/v1/promos',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Update
    'WebsiteApp',
    'Promo',
    'Edit',
    'Promo',
    'Edit',
    'PUT',
    '/web/v1/promos/:id',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Update Status
    'WebsiteApp',
    'Promo',
    'UpdateStatus',
    'Promo',
    'Update Status',
    'PUT',
    '/web/v1/promos/:id/status',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Create Promo Document
    'WebsiteApp',
    'Promo',
    'CreatePromoDocument',
    'Promo',
    'Create Promo Document',
    'POST',
    '/web/v1/promos/:id/document',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Update Promo Document
    'WebsiteApp',
    'Promo',
    'UpdatePromoDocument',
    'Promo',
    'Update Promo Document',
    'PUT',
    '/web/v1/promos/:id/document/:documentID',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Delete Promo Document
    'WebsiteApp',
    'Promo',
    'DeletePromoDocument',
    'Promo',
    'Delete Promo Document',
    'DELETE',
    '/web/v1/promos/:id/document/:documentID',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    0
  ), ( -- Approve Promo
    'WebsiteApp',
    'Promo',
    'ApprovePromo',
    'Promo',
    'Approve Promo',
    'PUT',
    '/web/v1/promos/:id/approve',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  ), ( -- Reject Promo
    'WebsiteApp',
    'Promo',
    'RejectPromo',
    'Promo',
    'Reject Promo',
    'PUT',
    '/web/v1/promos/:id/reject',
    'promos',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  );