INSERT INTO
  `permission`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by
  )
VALUES
  (
    'WebsiteAdmin',
    'Employee',
    'List',
    'Employee',
    'List',
    'GET',
    '/admin/v1/employees',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'View',
    'Employee',
    'View',
    'GET',
    '/admin/v1/employees/:id',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'Create',
    'Employee',
    'Create',
    'POST',
    '/admin/v1/employees',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'Edit',
    'Employee',
    'Edit',
    'PUT',
    '/admin/v1/employees/:id',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'EditPassword',
    'Employee',
    'Edit Password',
    'PUT',
    '/admin/v1/employees/:id/password',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'ResetPassword',
    'Employee',
    'Reset Password',
    'PUT',
    '/admin/v1/employees/:id/reset-password',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Employee',
    'UpdateStatus',
    'Employee',
    'Update Status',
    'PUT',
    '/admin/v1/employees/:id/status',
    'employees',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  );