INSERT INTO
  `permission`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by
  )
VALUES
  (
    'WebsiteAdmin',
    'Company',
    'List',
    'Company',
    'List',
    'GET',
    '/admin/v1/companies',
    'companies',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Company',
    'View',
    'Company',
    'View',
    'GET',
    '/admin/v1/companies/:id',
    'companies',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Company',
    'Create',
    'Company',
    'Create',
    'POST',
    '/admin/v1/companies',
    'companies',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Company',
    'Edit',
    'Company',
    'Edit',
    'PUT',
    '/admin/v1/companies/:id',
    'companies',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Company',
    'UpdateStatus',
    'Company',
    'Update Status',
    'PUT',
    '/admin/v1/companies/:id/status',
    'companies',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  );