INSERT INTO
  `permissions`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    sequence_number_detail,
    created_at,
    created_by,
    updated_at,
    updated_by,
    is_hidden
  )
VALUES
  (
    'WebsiteAdmin',
    'Permission',
    'List',
    'Permission',
    'List',
    'GET',
    '/admin/v1/permissions',
    'permissions',
    1,
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  );