INSERT INTO
  `permission`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by,
    is_hidden
  )
VALUES
  (
    'WebsiteApp',
    'Brand',
    'List',
    'Brand',
    'List',
    'GET',
    '/web/v1/brands',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  ), (
    'WebsiteApp',
    'Brand',
    'View',
    'Brand',
    'View',
    'GET',
    '/web/v1/brands/:id',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  );