INSERT INTO
  `permission`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by
  )
VALUES
  (
    'WebsiteAdmin',
    'Brand',
    'List',
    'Brand',
    'List',
    'GET',
    '/admin/v1/brands',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Brand',
    'View',
    'Brand',
    'View',
    'GET',
    '/admin/v1/brands/:id',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Brand',
    'Create',
    'Brand',
    'Create',
    'POST',
    '/admin/v1/brands',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Brand',
    'Edit',
    'Brand',
    'Edit',
    'PUT',
    '/admin/v1/brands/:id',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  ), (
    'WebsiteAdmin',
    'Brand',
    'UpdateStatus',
    'Brand',
    'Update Status',
    'PUT',
    '/admin/v1/brands/:id/status',
    'brands',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0'
  );