INSERT INTO
  `permissions`(
    package,
    module_name,
    action_name,
    display_module_name,
    display_action_name,
    http_method,
    route,
    table_name,
    created_at,
    created_by,
    updated_at,
    updated_by,
    is_hidden
  )
VALUES
  (
    'WebsiteApp',
    'Business',
    'View',
    'Business',
    'View',
    'GET',
    '/web/v1/business',
    'business',
    CURRENT_TIMESTAMP,
    '0',
    CURRENT_TIMESTAMP,
    '0',
    1
  );