CREATE TABLE promos (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) DEFAULT '',
  code VARCHAR(255) DEFAULT '',
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  img_url LONGTEXT NOT NULL,
  company_id VARCHAR(255) NOT NULL,
  business_id VARCHAR(255) NOT NULL,
  brand_id VARCHAR(255) NOT NULL,
  total_promo_budget DECIMAL(25,2) DEFAULT 0.0,
  principle_support DECIMAL(25,2) DEFAULT 0.0,
  internal_support DECIMAL(25,2) DEFAULT 0.0,
  description TEXT NOT NULL,
  approved_at DATETIME DEFAULT NULL,
  approved_by VARCHAR(255) DEFAULT '',
  rejected_at DATETIME DEFAULT NULL,
  rejected_by VARCHAR(255) DEFAULT '',
  reject_reason VARCHAR(255) DEFAULT '',

  status_id VARCHAR(5) DEFAULT '1', 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(255) DEFAULT '',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255) DEFAULT '',

  PRIMARY KEY (id),
  INDEX idx_company_id (company_id),
  INDEX idx_business_id (business_id),
  INDEX idx_brand_id (brand_id),
  INDEX idx_approved_by (approved_by),
  INDEX idx_rejected_by (rejected_by),
  INDEX idx_status_id (status_id)
);